create table "public"."ciudad" (
    "id" bigint generated by default as identity not null,
    "nombre_ciudad" character varying not null
);


alter table "public"."ciudad" enable row level security;

alter table "public"."empleado" add column "id_ciudad" bigint;

CREATE UNIQUE INDEX ciudad_pkey ON public.ciudad USING btree (id);

alter table "public"."ciudad" add constraint "ciudad_pkey" PRIMARY KEY using index "ciudad_pkey";

alter table "public"."empleado" add constraint "empleado_id_ciudad_fkey" FOREIGN KEY (id_ciudad) REFERENCES ciudad(id) not valid;

alter table "public"."empleado" validate constraint "empleado_id_ciudad_fkey";

grant delete on table "public"."ciudad" to "anon";

grant insert on table "public"."ciudad" to "anon";

grant references on table "public"."ciudad" to "anon";

grant select on table "public"."ciudad" to "anon";

grant trigger on table "public"."ciudad" to "anon";

grant truncate on table "public"."ciudad" to "anon";

grant update on table "public"."ciudad" to "anon";

grant delete on table "public"."ciudad" to "authenticated";

grant insert on table "public"."ciudad" to "authenticated";

grant references on table "public"."ciudad" to "authenticated";

grant select on table "public"."ciudad" to "authenticated";

grant trigger on table "public"."ciudad" to "authenticated";

grant truncate on table "public"."ciudad" to "authenticated";

grant update on table "public"."ciudad" to "authenticated";

grant delete on table "public"."ciudad" to "service_role";

grant insert on table "public"."ciudad" to "service_role";

grant references on table "public"."ciudad" to "service_role";

grant select on table "public"."ciudad" to "service_role";

grant trigger on table "public"."ciudad" to "service_role";

grant truncate on table "public"."ciudad" to "service_role";

grant update on table "public"."ciudad" to "service_role";


