name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Supabase CLI
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Paso 3: Probar conexión a la base de datos
      - name: Test Database Connection
        run: |
          echo "Testing connection to the database..."
          supabase db reset --db-url $DATABASE_URL --non-interactive || echo "Connection test failed"

      # Paso 4: Ejecutar migraciones de la base de datos
      - name: Run database migrations
        run: |
          echo "Running database migrations..."
          supabase db push --db-url $DATABASE_URL --debug
